require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-tree")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.comment")
require("plugins.gitsigns")
-- lsp
require("plugins.lsp.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.null-ls")
